# Generated by Django 4.1.6 on 2023-07-08 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name': 'página', 'verbose_name_plural': 'páginas'},
        ),
        migrations.RemoveField(
            model_name='page',
            name='order',
        ),
        migrations.AlterField(
            model_name='page',
            name='content',
            field=models.TextField(verbose_name='Contenido'),
        ),
    ]
